name: Build Code

on: [push, pull_request]

jobs:
  jobs1:
    runs-on: ubuntu-latest
    steps:
      - name: checking repo
        uses: actions/checkout@v2
      - name: Installing python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Update pip
        run: python -m pipt install --upgrade pip
      - name: Install Dependencies
        run: pip install -r requirements.txt